version: "3.8"

services: 
    mariadb:
        image: mariadb:10.2
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=trojan
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=trojan

        ports: 
            - "3306:3306"
        volumes: 
            - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/mariadb:/var/lib/mysql
    trojan:
        image: jrohy/trojan
        container_name: trojan
        privileged: true
        restart: always
        volumes:
            - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/trojan:/cert
        stdin_open: true
        tty: true
        network_mode: "host"
        command: 
            - init
        